LD_LIBRARY_PATH=/usr/local/lib
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/zhou822/GTX/build/
export LD_LIBRARY_PATH
numactl -N 1 -l /home/zhou822/gfe_driver_gtx/build/gfe_driver -G /home/zhou822/gfe_experiment_data/graph_source/graph500-24.properties  -R 3 -u --log /home/zhou822/test_log/test0.graphlog --aging_timeout 24h -l gtx_rw -w 16 -r 16 --blacklist sssp,cdlp,bfs,wcc,lcc --mixed_workload true
numactl -N 1 -l /home/zhou822/gfe_driver_gtx/build/gfe_driver -G /home/zhou822/gfe_experiment_data/graph_source/graph500-24.properties  -R 3 -u --log /home/zhou822/test_log/test0.graphlog --aging_timeout 24h -l gtx_rw -w 16 -r 32 --blacklist sssp,cdlp,bfs,wcc,lcc --mixed_workload true
numactl -N 1 -l /home/zhou822/gfe_driver_gtx/build/gfe_driver -G /home/zhou822/gfe_experiment_data/graph_source/graph500-24.properties  -R 3 -u --log /home/zhou822/test_log/test0.graphlog --aging_timeout 24h -l gtx_rw -w 16 -r 48 --blacklist sssp,cdlp,bfs,wcc,lcc --mixed_workload true
numactl -N 1 -l /home/zhou822/gfe_driver_gtx/build/gfe_driver -G /home/zhou822/gfe_experiment_data/graph_source/graph500-24.properties  -R 3 -u --log /home/zhou822/test_log/test0.graphlog --aging_timeout 24h -l gtx_rw -w 32 -r 32 --blacklist sssp,cdlp,bfs,wcc,lcc --mixed_workload true
numactl -N 1 -l /home/zhou822/gfe_driver_gtx/build/gfe_driver -G /home/zhou822/gfe_experiment_data/graph_source/graph500-24.properties  -R 3 -u --log /home/zhou822/test_log/test0.graphlog --aging_timeout 24h -l gtx_rw -w 32 -r 16 --blacklist sssp,cdlp,bfs,wcc,lcc --mixed_workload true
numactl -N 1 -l /home/zhou822/gfe_driver_gtx/build/gfe_driver -G /home/zhou822/gfe_experiment_data/graph_source/graph500-24.properties  -R 3 -u --log /home/zhou822/test_log/test0.graphlog --aging_timeout 24h -l gtx_rw -w 40 -r 24 --blacklist sssp,cdlp,bfs,wcc,lcc --mixed_workload true
numactl -N 1 -l /home/zhou822/gfe_driver_gtx/build/gfe_driver -G /home/zhou822/gfe_experiment_data/graph_source/graph500-24.properties  -R 3 -u --log /home/zhou822/test_log/test0.graphlog --aging_timeout 24h -l gtx_rw -w 48 -r 16 --blacklist sssp,cdlp,bfs,wcc,lcc --mixed_workload true
